#!/bin/bash
# onebusaway-king-county-metro-legacy-avl-to-siri Start and stop the LegacyAVL-to-SIRI proces
#
# chkconfig: 345 75 25
# description: onebusaway-king-county-metro-legacy-avl-to-siri - An application for converting legacy AVL packets into a SIRI VM stream
# pidfile: /var/run/onebusaway-king-county-metro-legacy-avl-to-siri.pid
# config: /etc/onebusaway-king-county-metro-legacy-avl-to-siri/onebusaway-king-county-metro-legacy-avl-to-siri.conf
### BEGIN INIT INFO
# Provides: onebusaway-king-county-metro-legacy-avl-to-siri
# Required-Start: $network $syslog
# Required-Stop: $network $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Description: LegacyAVL-to-SIRI application
# Short-Description: start and stop onebusaway-king-county-metro-legacy-avl-to-siri
### END INIT INFO
#
#

if [ -r /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
else
    exit 1
fi

NAME="$(basename $0)"
unset ISBOOT
if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
    NAME="${NAME:3}"
    ISBOOT="1"
fi

# For SELinux we need to use 'runuser' not 'su'
if [ -x "/sbin/runuser" ]; then
    SU="/sbin/runuser"
else
    SU="su"
fi

# Get the config (use this for environment specific settings)
CONFIG_FILE="/etc/onebusaway-king-county-metro-legacy-avl-to-sirionebusaway-king-county-metro-legacy-avl-to-siri.conf"
if [ -r "$CONFIG_FILE" ]; then
    . ${CONFIG_FILE}
fi

# Get instance specific config file
if [ -r "/etc/sysconfig/${NAME}" ]; then
    . /etc/sysconfig/${NAME}
fi

PACKET_HOST="${PACKET_HOST:-146.129.150.20}"
PACKET_PORT="${PACKET_PORT:-5001}"

# Path to the jar
JAR_FILE="${JAR_FILE:-/usr/share/onebusaway-king-county-metro-legacy-avl-to-siri/onebusaway-king-county-metro-legacy-avl-to-siri.jar}"

# Define the tomcat username
OBA_USER="${OBA_USER:-root}"
OBA_GROUP="${OBA_GROUP:-root}"

# Define the log file
LOG_FILE="${LOG_FILE:-/var/log/onebusaway-king-county-metro-legacy-avl-to-siri/onebusaway-king-county-metro-legacy-avl-to-siri.log}"

# Define the java executable
JAVA="${JAVA:-java}"

# Define the PID file
PID_FILE="/var/run/${NAME}.pid"
LOCK_FILE="/var/lock/subsys/${NAME}"

CLI_ARGS="${CLI_ARGS:-}"

# Define th command to launch the application
APP_CMD="tcpdump -U -w - host ${PACKET_HOST} and port ${PACKET_PORT} | java -jar ${JAR_FILE} ${CLI_ARGS}" 

RETVAL="0"

function checkpid() {
    local i
    for i in $* ; do
        if [ -d "/proc/${i}" ]; then
            return 0
        fi
    done
    return 1
}

# See how we were called.
function start() {
    echo -n "Starting ${NAME}: "
    if [ -f "${LOCK_FILE}" ] ; then
        if [ -f "${PID_FILE}" ]; then
            read kpid < $PID_FILE
                if checkpid $kpid 2>&1; then
                    echo "$NAME process already running"
                        return -1
                    else
                        echo "lock file found but no process running for"
                        echo "pid $kpid, continuing"
                fi
        fi
    fi

    # Make sure the PID file has proper ownership
    touch $PID_FILE
    chown ${OBA_USER} $PID_FILE

    # Make sure the log file has proper ownership
    touch $LOG_FILE
    chown ${OBA_USER}:${OBA_GROUP} $LOG_FILE

    # We double background the process to detach it from the parent tty "(cmd &) &"
    $SU - $OBA_USER -c "(${APP_CMD} >> $LOG_FILE 2>&1 &)&" 
    RETVAL="$?"
    if [ "$RETVAL" -eq 0 ]; then
        # We need to grab the PID of the tcpdump process.  We grep on the
        # packet host in case multiple instance are running
        ps aux | grep tcpdump | grep ${PACKET_HOST} | awk '{ print $2 }' > $PID_FILE 
        log_success_msg
        touch $LOCK_FILE
    else
        log_failure_msg
    fi
    #echo
    return $RETVAL
}

function status() {
    RETVAL="1"
    if [ -f "${PID_FILE}" ]; then
        read kpid < $PID_FILE
        if checkpid $kpid 2>&1; then
            echo "$0 is already running (${kpid})"
            RETVAL="0"
        else
            echo "lock file found but no process running for pid $kpid"
        fi
    else
        pid="$(pgrep -u ${OBA_USER} tcpdump)"
        if [ -n "$pid" ]; then
            echo "$0 running (${pid}) but no PID file exists"
            RETVAL="0"
        else
            echo "$0 is stopped"
        fi
    fi
    return $RETVAL
}

function stop() {
    echo -n "Stopping $NAME: "
    if [ -f "${LOCK_FILE}" ]; then
        if [ -f "${PID_FILE}" ]; then
            read kpid < $PID_FILE
            kill $kpid
            log_success_msg
        else
            log_failure_msg
        fi
        rm -f $LOCK_FILE $PID_FILE
    else
        log_failure_msg
    fi
    #echo
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 2    
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|status|version}"
        exit 1
esac

exit $RETVAL
